title: Gustavo Santelices N.
email: gsantelicesn2@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A student page thought to be used as a fun way to present himself.
twitter_username: QwagPerson
github_username:  QwagPerson

# Build settings
theme: jekyll-theme-cayman

show_downloads: false
google_analytics: UA-213536068-1

twitter: https://twitter.com/
facebook: https://facebook.com/
instagram: https://instagram.com/
show_socials: true

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
